begin
  require 'rspec/core/rake_task'
rescue LoadError
  puts "\nRspec 2 is required. Try this: \n\t`gem install rspec-core rspec-expectations`.\n\n"
  raise
end

vagrant_dir = File.join(File.dirname(__FILE__), 'vagrant')

desc "Deploy a fresh vagrant instance (destroying an existing instance)."
task :deploy do
  cd vagrant_dir do
    sh 'vagrant destroy'
    sh 'vagrant up'
  end
end

desc "Re-provision running instance from local chef cookbooks."
task :reprovision do
  cd vagrant_dir do
    sh 'vagrant provision'
  end
end

task :setup_ssh do
  cd vagrant_dir do
    sh "vagrant ssh_config > vagrant.ssh.config"
    ENV['SSH_OPTIONS'] = "-F #{File.expand_path('vagrant.ssh.config')}"
    ENV['SSH_HOST'] = "vagrant"
  end
end

RSpec::Core::RakeTask.new('system_spec') do |t|
  t.rspec_opts = ["--color", "--format documentation", "--require ./spec_helper.rb"]
  t.pattern = '*_spec.rb'
end
task 'system_spec' => 'setup_ssh'

desc "Run system specs on an existing instance."
task :default => 'system_spec'

desc "Deploy fresh instance and run system specs."
task :full => %w( deploy system_spec )

namespace :ec2 do
  task :full do
    require 'AWS'
    require 'pry'
    with_ec2_instance do |instance|
      sh %(tar czf ../../RapidFTR-chef-repo-test.tgz --directory ../.. chef-repo)
      puts "sleeping 5"; sleep 5
      sh %(scp #{ENV['SSH_OPTIONS']} ../../RapidFTR-chef-repo-test.tgz #{ENV['SSH_HOST']}:)
      sh %(scp #{ENV['SSH_OPTIONS']} vagrant/localhost.rapidftr.test.crt #{ENV['SSH_HOST']}:)
      sh %(scp #{ENV['SSH_OPTIONS']} vagrant/localhost.rapidftr.test.key #{ENV['SSH_HOST']}:)
      sh %(ssh #{ENV['SSH_OPTIONS']} #{ENV['SSH_HOST']} "tar xzf RapidFTR-chef-repo-test.tgz")
      sh %(ssh #{ENV['SSH_OPTIONS']} #{ENV['SSH_HOST']} "export SSL_CRT=~/localhost.rapidftr.test.crt && export SSL_KEY=~/localhost.rapidftr.test.key && export FQDN=#{instance.dnsName} && cd chef-repo/ && sudo ./setup-ubuntu.sh")
      sh %(ssh #{ENV['SSH_OPTIONS']} #{ENV['SSH_HOST']} "sudo chef-solo")
      Rake::Task['system_spec'].invoke
    end
  end
end

def with_ec2_instance
  ec2 = AWS::EC2::Base.new(
    :access_key_id => ENV['AMAZON_ACCESS_KEY_ID'],
    :secret_access_key => ENV['AMAZON_SECRET_ACCESS_KEY'])
  ami = "ami-7000f019" # Ubuntu 10.04 LTS Lucid instance-store from http://alestic.com/
  puts "Launching instance with AMI #{ami}"
  r = ec2.run_instances(
    :image_id => ami,
    :disable_api_termination => false,
    :instance_type => "c1.medium",
    :key_name => File.basename(ENV['RAPID_FTR_IDENTITY_FILE'], '.pem'))
  instance_id = r.instancesSet.item.first.instanceId
  instance = nil
  begin
    puts "Waiting for instance #{instance_id} to be running."
    sleep 8
    description = ec2.describe_instances(:instance_id => instance_id)
    instance = description.reservationSet.item[0].instancesSet.item[0]
    puts "Instance is #{instance.instanceState.name}"
  end while instance.instanceState.name != "running"

  File.open('aws.ssh.config', 'w') do |file|
    file.write "Host ec2
      HostName #{instance.dnsName}
      User ubuntu
      UserKnownHostsFile /dev/null
      StrictHostKeyChecking no
      PasswordAuthentication no
      IdentityFile #{File.expand_path(ENV['RAPID_FTR_IDENTITY_FILE'])}
      IdentitiesOnly yes"
    file.puts
  end
  ENV['SSH_OPTIONS'] = "-F #{File.expand_path('aws.ssh.config')}"
  ENV['SSH_HOST'] = "ec2"

  yield instance

ensure
  puts "Terminating instance #{instance_id}."
  pry
  ec2.terminate_instances :instance_id => [instance_id]
end
