begin
  require 'rspec/core/rake_task'
rescue LoadError
  puts "\nRspec 2 is required. Try this: \n\t`gem install rspec-core rspec-expectations`.\n\n"
  raise
end

vagrant_dir = File.join(File.dirname(__FILE__), 'vagrant')

desc "Deploy a fresh vagrant instance (destroying an existing instance)."
task :deploy do
  cd vagrant_dir do
    sh 'vagrant destroy'
    sh 'vagrant up'
  end
end

desc "Re-provision running instance from local chef cookbooks."
task :reprovision do
  cd vagrant_dir do
    sh 'vagrant provision'
  end
end

task :setup_ssh do
  cd vagrant_dir do
    sh "vagrant ssh_config > vagrant.ssh.config"
    ENV['SSH_CONFIG'] = File.expand_path(
      File.dirname(__FILE__) + '/vagrant/vagrant.ssh.config')
  end
end

RSpec::Core::RakeTask.new('system_spec') do |t|
  t.rspec_opts = ["--color", "--format documentation", "--require ./spec_helper.rb"]
  t.pattern = '*_spec.rb'
end
task 'system_spec' => 'setup_ssh'

desc "Run system specs on an existing instance."
task :default => 'system_spec'

desc "Deploy fresh instance and run system specs."
task :full => %w( deploy system_spec )
