#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'git', '2.0.0'
cookbook 'erlang', '1.1.2'
cookbook 'spidermonkey', '0.0.1', :path => 'custom-cookbooks/spidermonkey'
cookbook 'couchdb', '2.1.0'
cookbook 'passenger', '0.0.1'
cookbook 'java', '1.9.2'
cookbook 'imagemagick', '0.2.2'
cookbook 'rapidftr_ssl', '0.0.1', :path => 'custom-cookbooks/rapidftr_ssl'
