#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'git', '2.0.0'
cookbook 'couchdb', '1.0.4'
cookbook 'passenger', '0.0.1'
cookbook 'java', '1.6.4'
cookbook 'rapidftr_ssl', '0.0.1', :path => 'custom-cookbooks/rapidftr_ssl'
