Vagrant::Config.run do |config|
  config.vm.box = "lucid32"
  config.vm.forward_port("http", 80, 8080)
  config.vm.forward_port("https", 443, 443)

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../../cookbooks"
    chef.roles_path = "../../roles"

    chef.add_role "default"

    # SSL certs generated as shown on http://www.akadia.com/services/ssh_test_certificate.html
    chef.json[:rapid_ftr] = {
      :ssl_certificate => "/vagrant/localhost.rapidftr.test.crt",
      :ssl_certificate_key => "/vagrant/localhost.rapidftr.test.key"
    }
    chef.json[:passenger] = {:production => {:bins_path => "/usr/bin"}}
  end

end
